import '../globals.css'
import Header from "@/src/components/common/Partials/Header/Header"
import Footer from '@/src/components/common/Partials/Footer/Footer'

export const metadata = {
  title: 'Next.js Starter',
  description: 'Generated by create next app',
  ogTitle: 'Next.js Starter',
  ogDescription: 'Generated by create next app',
  // ogImage: '/images/og-image.jpg',
}

export default function RootLayout({ children }) {
  return (
    <>
        <Header />
        <main className='w-[100%] h-[100%]'>
            {children}
        </main>
        <Footer />
    </>
  )
}
