import '../globals.css'
import Header from "@/src/components/common/Partials/Header/Header"
import Footer from '@/src/components/common/Partials/Footer/Footer'
import { decodeSession } from '@/src/lib/decodeSession'
import { Discord } from '../../components/common/Global/Icons/BrandLogos/Discord'
import NavItem from '../../components/common/Partials/Header/Navigation/NavItem/NavItem'
import Github from '../../components/common/Global/Icons/BrandLogos/Github'
import Profile from '../../components/common/Global/Profile'

export const metadata = {
  title: 'Next.js Starter',
  description: 'Generated by create next app',
  ogTitle: 'Next.js Starter',
  ogDescription: 'Generated by create next app',
  // ogImage: '/images/og-image.jpg',
}

export default async function RootLayout({ children }) {

  const session = await decodeSession();

  return (
    <>
        <Header>
        <nav
      className="w-[1500px] bg-transparent h-full flex flex-row justify-between"
      session={session}
    >
      <ul className="w-[300px] h-full flex items-center">
        <li className="rounded-full border pb-[2px] border-vtertiary bg-vsecondary/[.14]">
          <NavItem link="/" isLogo={true} text="DICE." />
        </li>
      </ul>
      <ul className="w-[640px] h-full flex items-center">
        <li className="border-r border-zinc-700/70 pr-5 flex">
          <NavItem link="/" text="Accueil" />
          <NavItem link="/jeux" text="Jeux" />
          <NavItem link="/actus" text="Actualités" />
          <NavItem link="/contact" text="Contact" />
          {session ? (
            /**
             * @todo
             *
             */

            <Profile />
          ) : (
            <NavItem link="/connexion" text="Connexion" />
          )}
        </li>
        <li className="flex flex-row h-[24px] items-center px-5 whitespace-nowrap border-r border-zinc-700/70 ">
          <NavItem link="/versions" text="Version : 1.0.0" />
        </li>
        <li className="flex flex-row pl-5 h-[24px] items-center gap-1">
          <Discord />
          <Github />
        </li>
      </ul>
    </nav>
        </Header>
        <main className='w-[100%] h-[100%]'>
            {children}
        </main>
        <Footer />
    </>
  )
}

