import './globals.css'
import Header from "../components/common/Partials/Header/Header"
import Footer from '@/components/common/Partials/Footer/Footer'
import { poppins, montserrat, ubuntu } from './fonts'

export const metadata = {
  title: 'Next.js Starter',
  description: 'Generated by create next app',
  ogTitle: 'Next.js Starter',
  ogDescription: 'Generated by create next app',
  // ogImage: '/images/og-image.jpg',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={poppins.className}>
      <body className='bg-[#1E1E20]'>
        <Header />
        <main className='w-[100%] h-[100%]'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
