import './globals.css'
import Header from "../components/common/Partials/Header/Header"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className='bg-[#1E1E20]'>
        <Header />
        <main className='w-[100%] h-[100%]'>
          {children}
        </main>
      </body>
    </html>
  )
}
