import './globals.css'
import Header from "@/src/components/common/Partials/Header/Header"
import Footer from '@/src/components/common/Partials/Footer/Footer'
import { poppins, montserrat, ubuntu } from './fonts'
import Providers from '../components/common/Global/Providers'
import AuthProvider from '../components/common/Global/AuthProvider'

export const metadata = {
  title: 'Next.js Starter',
  description: 'Generated by create next app',
  ogTitle: 'Next.js Starter',
  ogDescription: 'Generated by create next app',
  // ogImage: '/images/og-image.jpg',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={poppins.className}>
      <body className='bg-[#1E1E20]'>
      <AuthProvider>
        {children}
      </AuthProvider>
      </body>
    </html>
  )
}
